/**
 * Spell names as the remaster prints them.
 *
 * Imported ability prose names spells the source game's way, and the legacy
 * PF2e names many of them share were renamed by the remaster. The AI rewrite
 * cannot be trusted to know the list, so it lives here as data and is applied
 * deterministically - including over the AI's output.
 *
 * The list is the pf2e system's own Remaster Changes journal (packs/pf2e/
 * journals/remaster-changes.json, which supersedes the wiki page and fixed
 * its swapped dimensional anchor/lock rows),
 * merged with a curated set of 5th-edition names whose PF2e counterpart is
 * unambiguous (charm person is charm, cure wounds is heal), then validated
 * against the system's spells compendium with two rules enforced by
 * check-spellnames.mjs: every target must be a real spell, and no source may
 * shadow one - a name the compendium still knows (acid splash, phantasmal
 * killer) resolves directly and is deliberately NOT in this map, because
 * renaming it would swap a real spell for a different one.
 */
export const SPELL_RENAMES = {
  "abundant step": "shrink the span",
  "abyssal wrath": "chthonian wrath",
  "animate dead": "summon undead",
  "augment summoning": "fortify summoning",
  "baleful polymorph": "cursed metamorphosis",
  "barkskin": "oaken resilience",
  "bind soul": "seize soul",
  "blind ambition": "ignite ambition",
  "blink": "flicker",
  "burning hands": "breathe fire",
  "calm emotions": "calm",
  "charm person": "charm",
  "charming words": "charming push",
  "chill touch": "void warp",
  "cloudkill": "toxic cloud",
  "color spray": "dizzying colors",
  "commune with nature": "commune",
  "comprehend language": "translate",
  "continual flame": "everlight",
  "crushing despair": "wave of despair",
  "cure wounds": "heal",
  "dancing lights": "light",
  "detect thoughts": "mind reading",
  "dimension door": "translocate",
  "dimensional anchor": "planar tether",
  "dimensional lock": "planar seal",
  "discern location": "pinpoint",
  "disguise self": "illusory disguise",
  "disrupt undead": "vitality lash",
  "disrupting weapons": "infuse vitality",
  "dragon claws": "flurry of claws",
  "efficient apport": "reclined apport",
  "empty body": "embrace nothingness",
  "endure elements": "environmental endurance",
  "entangle": "entangling flora",
  "expeditious retreat": "fleet step",
  "false life": "false vitality",
  "feather fall": "gentle landing",
  "feeblemind": "never mind",
  "finger of death": "execute",
  "flaming sphere": "floating flame",
  "flesh to stone": "petrify",
  "floating disk": "carryall",
  "force cage": "lifewood cage",
  "freedom of movement": "unfettered movement",
  "gaseous form": "vapor form",
  "gentle repose": "peaceful rest",
  "glibness": "honeyed words",
  "glitterdust": "revealing light",
  "globe of invulnerability": "dispelling globe",
  "glutton's jaw": "glutton's jaws",
  "glyph of warding": "rune trap",
  "goodberry": "cornucopia",
  "greater invisibility": "invisibility",
  "greater restoration": "restoration",
  "hallucinatory terrain": "mirage",
  "heroes' feast": "fortifying brew",
  "hideous laughter": "laughing fit",
  "hold person": "paralyze",
  "horrid wilting": "desiccate",
  "hyperfocus": "clouded focus",
  "hypnotic pattern": "hypnotize",
  "inflict wounds": "harm",
  "inspire competence": "uplifting overture",
  "inspire courage": "courageous anthem",
  "inspire defense": "rallying anthem",
  "inspire heroics": "fortissimo composition",
  "invisibility sphere": "shared invisibility",
  "ki blast": "qi blast",
  "ki form": "qi form",
  "ki rush": "qi rush",
  "ki strike": "inner upheaval",
  "know direction": "know the way",
  "legend lore": "collective memories",
  "lesser restoration": "restoration",
  "longstrider": "tailwind",
  "mage armor": "mystic armor",
  "mage hand": "telekinetic hand",
  "magic aura": "disguise magic",
  "magic fang": "runic body",
  "magic missile": "force barrage",
  "magic mouth": "embed message",
  "magic weapon": "runic weapon",
  "magnificent mansion": "planar palace",
  "maze": "quandary",
  "meld into stone": "one with stone",
  "meteor swarm": "falling stars",
  "mind blank": "hidden mind",
  "minor illusion": "figment",
  "misdirection": "disguise magic",
  "misty step": "translocate",
  "modify memory": "rewrite memory",
  "neutralize poison": "cleanse affliction",
  "nondetection": "veil of privacy",
  "obscuring mist": "mist",
  "pass without trace": "vanishing tracks",
  "passwall": "magic passage",
  "phantom mount": "marvelous mount",
  "planar binding": "planar servitor",
  "plane shift": "interplanar teleport",
  "positive luminance": "vital luminance",
  "private sanctum": "peaceful bubble",
  "produce flame": "ignition",
  "prying eye": "scouting eye",
  "pulse of the city": "pulse of civilization",
  "purify food and drink": "cleanse cuisine",
  "quivering palm": "touch of death",
  "ray of enfeeblement": "enfeeble",
  "remove curse": "cleanse affliction",
  "remove disease": "cleanse affliction",
  "remove fear": "clear mind",
  "remove paralysis": "sure footing",
  "resilient sphere": "containment",
  "restore senses": "sound body",
  "righteous might": "sacred form",
  "roar of the wyrm": "roar of the dragon",
  "sanctified ground": "anointed ground",
  "scintillating pattern": "confusing colors",
  "scorching ray": "blazing bolt",
  "searing light": "holy light",
  "see invisibility": "see the unseen",
  "shadow walk": "umbral journey",
  "shapechange": "metamorphosis",
  "shield other": "share life",
  "simulacrum": "shadow double",
  "sound burst": "noise blast",
  "spectral hand": "ghostly carrier",
  "spider climb": "gecko grip",
  "splash of art": "creative splash",
  "stone tell": "speak with stones",
  "stoneskin": "mountain resilience",
  "tanglefoot": "tangle vine",
  "time stop": "freeze time",
  "tongues": "truespeech",
  "touch of corruption": "touch of the void",
  "touch of idiocy": "stupefy",
  "tree shape": "one with plants",
  "tree stride": "nature's pathway",
  "true strike": "sure strike",
  "trueseeing": "truesight",
  "unseen custodians": "phantasmal custodians",
  "unseen servant": "phantasmal minion",
  "vampiric touch": "vampiric feast",
  "veil": "illusory disguise",
  "vigilant eye": "rune of observation",
  "wail of the banshee": "wails of the damned",
  "wholeness of body": "harmonize self",
  "wind walk": "migration",
  "word of recall": "gathering call",
  "zone of truth": "ring of truth",
};

// Longest first, so "vampiric touch" can never eat the front of a longer
// name and leave the remainder dangling.
const PATTERN = new RegExp(
  `\\b(${Object.keys(SPELL_RENAMES)
    .sort((a, b) => b.length - a.length)
    .join('|')})\\b`,
  'gi',
);

/** Rewrite known spell names in prose, preserving a leading capital. */
export function modernizeSpellNames(text) {
  return String(text ?? '').replace(PATTERN, (match) => {
    const replacement = SPELL_RENAMES[match.toLowerCase()];
    return match[0] === match[0].toUpperCase()
      ? replacement.charAt(0).toUpperCase() + replacement.slice(1)
      : replacement;
  });
}
